export const data = {
  products: [
    {
      id: '1',
      name: '가죽 숄더백',
      image: '/images/가방1.jpg',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description:
        '가죽과 흡사하면서도 편의성을 갖춘 Premium Vegan Leather를 사용하였습니다.',
    },
    {
      id: '2',
      name: '가죽 미디움 케미백',
      image: '/images/가방2.jpg',
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: '노트북 수납과 디자인 감성 + 실용성까지 더한 2way 데일리백',
    },
    {
      id: '3',
      name: '에센셜 메신져백 블랙',
      image: '/images/가방3.jpg',
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: '남녀노소 사용가능한 데일리 메신져백',
    },
    {
      id: '4',
      name: '앱솔루트 백팩 블랙',
      image: '/images/가방4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '월등한 수납능력, 노트북과 태블릿도 안전하게 수납',
    },
    {
      id: '5',
      name: '코지 L 크로스백',
      image: '/images/가방5.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '퀼티드 패턴의 수납력을 더 높힌 코지 라지백',
    },
    {
      id: '6',
      name: '3버튼 카라 니트 네이비',
      image: '/images/상의1.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '부드러운 소재로 짜인 카라 니트',
    },
    {
      id: '7',
      name: 'T-로고 크루넥 블랙',
      image: '/images/상의2.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '월등한 수납능력, 노트북과 태블릿도 안전하게 수납',
    },
    {
      id: '8',
      name: '핸섬 댄 후드',
      image: '/images/상의3.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '중량감 400g, 수축 최소화를 한 질 좋은 후드',
    },
    {
      id: '9',
      name: '클래식 로고 스웨트셔츠 블랙',
      image: '/images/상의4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '월등한 수납능력, 노트북과 태블릿도 안전하게 수납',
    },
    {
      id: '10',
      name: 'Thunder 브러쉬드 니트',
      image: '/images/상의5.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '매력적인 배색 조합의 그런지 무드 Thunder 브러쉬드 니트',
    },
    {
      id: '11',
      name: '포럼 로우 클래식 화이트',
      image: '/images/신발1.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '브랜드를 대표하는 스니커즈로 40여년 동안 사랑받아 왔습니다. 깊은 역사를 가진 농구화의 클래식 디자인에 모던한 터치를 녹여낸 새로운 버전을 만나보세요.',
    },
    {
      id: '12',
      name: '스탠스미스 - 화이트 그린',
      image: '/images/신발2.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '시대를 초월하는 자연스러움과 실용성. 50년이 넘는 시간 동안 큰 사랑을 받고 있는 아이코닉한 스탠 스미스를 만나보세요. 2024년부터 전면 재활용 폴리에스테르 사용을 목표로 하는 혁신적인 신개념 슈즈입니다.',
    },
    {
      id: '13',
      name: '퍼 카라 스웨이드 슬리퍼',
      image: '/images/신발3.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '최상급 트윈페이스 양가죽 소재로 고급스럽고 편안한 착화감 제공',
    },
    {
      id: '14',
      name: '빈티지 더비슈즈',
      image: '/images/신발4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '빈티지한 워싱 소가죽을 사용하여 제작된 더비슈즈입니다.',
    },
    {
      id: '15',
      name: '8홀 레이스 로우 부츠 블랙 ',
      image: '/images/신발5.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        ' 부드러우며 튼튼한 내구성과 내마모성을 자랑하는 Smooth Leather 소재 사용',
    },
    {
      id: '16',
      name: '벨란디 캐시미어 블렌드 발마칸 코트',
      image: '/images/아우터1.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '혼방하여 두께감을 높인 이중직 아이템. 뜨거운물에 장시간 펠팅 처리를하여 컴팩트함을 살린 후, 부드러운 촉감을 위해 정밀한 브러싱을 하였습니다.',
    },
    {
      id: '17',
      name: '스카디 덕 다운 ',
      image: '/images/아우터2.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '생활방수가 되는 고급스러운 덕 다운',
    },
    {
      id: '18',
      name: '솔리드 무톤 자켓',
      image: '/images/아우터3.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '함모량을 극대화로 늘려 밀도감, 방한성을 높였습니다. 또한, 특유의 감도 높은 퍼로 가벼운 활동성을 제공합니다.',
    },
    {
      id: '19',
      name: '남성 로고 트랙수트 자켓 ',
      image: '/images/아우터4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '세미오버핏으로 만들어진 고급스러운 트랙수트 자켓',
    },
    {
      id: '20',
      name: '여성 로고 스트라이프 울 가디건 - 멀티컬러',
      image: '/images/아우터5.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '울 함량 45% 로 보온성을 극대화시킨 두께감 있는 가디건',
    },
    {
      id: '21',
      name: '이지 와이드 데님 팬츠 그레이 ',
      image: '/images/하의1.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '와이드 핏으로 나온 그레이 데님 팬츠',
    },
    {
      id: '22',
      name: '원턱 와이드 스웨트 팬츠',
      image: '/images/하의2.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '장소, 시간에 구애받지 않는 ALL 시즌 필수 아이템으로 자리잡은 스웨트 팬츠',
    },
    {
      id: '23',
      name: '원턱 파라슈트 카고 데님팬츠_그레이',
      image: '/images/하의3.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '여유있는 실루엣이 특징인 전면 원턱 파라슈트 데님팬츠',
    },
    {
      id: '24',
      name: '1880 퓨어 크림 진',
      image: '/images/하의4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '세련된 크림 톤의 컬러감과 밀도 높은 질감을 표현하기 위하여 특수 가공 처리가 진행되었습니다',
    },
    {
      id: '25',
      name: 'Mid Rise 와이드 데님 팬츠',
      image: '/images/하의5.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '미드라이즈 와이드는 너무 길지 않은 밑위와 힙을 감싸주면서 허벅지부터 밑단까지 와이드한 핏의 데님팬츠입니다',
    },
  ],
}
