export const data = {
  products: [
    {
      id: '16',
      name: '벨란디 캐시미어 블렌드 발마칸 코트',
      image: '/images/아우터1.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '혼방하여 두께감을 높인 이중직 아이템. 뜨거운물에 장시간 펠팅 처리를하여 컴팩트함을 살린 후, 부드러운 촉감을 위해 정밀한 브러싱을 하였습니다.',
    },
    {
      id: '17',
      name: '스카디 덕 다운 ',
      image: '/images/아우터2.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '생활방수가 되는 고급스러운 덕 다운',
    },
    {
      id: '18',
      name: '솔리드 무톤 자켓',
      image: '/images/아우터3.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description:
        '함모량을 극대화로 늘려 밀도감, 방한성을 높였습니다. 또한, 특유의 감도 높은 퍼로 가벼운 활동성을 제공합니다.',
    },
    {
      id: '19',
      name: '남성 로고 트랙수트 자켓 ',
      image: '/images/아우터4.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '세미오버핏으로 만들어진 고급스러운 트랙수트 자켓',
    },
    {
      id: '20',
      name: '여성 로고 스트라이프 울 가디건 - 멀티컬러',
      image: '/images/아우터5.jpg',
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: '울 함량 45% 로 보온성을 극대화시킨 두께감 있는 가디건',
    },
  ],
}
